# Generated by Django 2.1.1 on 2018-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steelsensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
